include = ["**/*.toml"]
exclude = ["target/**", "**/Cargo.lock"]

[formatting]
align_entries     = true
align_comments    = true
indent_string     = "  "
trailing_newline  = true
column_width      = 120
reorder_keys      = false
reorder_arrays    = false

[[rule]]
include = ["**/Cargo.toml"]

[rule.formatting]
reorder_keys = false
